"""Bridges a Twilio Media Stream WebSocket to an OpenAI Realtime session.

Twilio's Media Streams and the OpenAI Realtime API can both speak G.711
mu-law audio natively, so this bridge relays base64 audio payloads back
and forth almost verbatim instead of running a separate
transcribe -> LLM -> TTS pipeline. See docs/ARCHITECTURE.md for why that
tradeoff was made.

Audio direction, concretely:
  Twilio inbound "media" event  -> OpenAI `input_audio_buffer.append`
    (this is the real Athena agent's voice, since Twilio is relaying the
    other end of the phone call)
  OpenAI `response.audio.delta` -> Twilio outbound "media" event
    (this is our simulated patient's voice, generated by the Realtime
    model from the scenario's system prompt)

Transcripts of both sides are captured from the Realtime API's own
transcription events (no separate STT pass needed) and appended to a
`TranscriptRecorder` as they arrive.
"""

from __future__ import annotations

import asyncio
import json
import logging
from typing import Any

import websockets
from fastapi import WebSocket, WebSocketDisconnect

from bot.config import Settings
from bot.personas import Scenario
from bot.transcript import SPEAKER_AGENT_UNDER_TEST, SPEAKER_PATIENT_BOT, TranscriptRecorder

logger = logging.getLogger(__name__)

OPENAI_REALTIME_URL = "wss://api.openai.com/v1/realtime"

# OpenAI Realtime server event types this bridge acts on.
EVENT_AUDIO_DELTA = "response.audio.delta"
EVENT_SPEECH_STARTED = "input_audio_buffer.speech_started"
EVENT_PATIENT_BOT_TRANSCRIPT_DONE = "response.audio_transcript.done"
EVENT_AGENT_UNDER_TEST_TRANSCRIPT_DONE = "conversation.item.input_audio_transcription.completed"
EVENT_ERROR = "error"


class RealtimeBridge:
    """Owns one call's Twilio <-> OpenAI Realtime audio + transcript bridge."""

    def __init__(
        self,
        settings: Settings,
        scenario: Scenario,
        recorder: TranscriptRecorder,
        voice: str = "alloy",
    ) -> None:
        self.settings = settings
        self.scenario = scenario
        self.recorder = recorder
        self.voice = voice
        self.stream_sid: str | None = None

    async def run(self, twilio_ws: WebSocket) -> None:
        """Drive one call end-to-end. Returns when either side hangs up."""
        await twilio_ws.accept()

        async with websockets.connect(
            f"{OPENAI_REALTIME_URL}?model={self.settings.openai_realtime_model}",
            additional_headers={
                "Authorization": f"Bearer {self.settings.openai_api_key}",
                "OpenAI-Beta": "realtime=v1",
            },
            max_size=None,
        ) as openai_ws:
            await self._configure_session(openai_ws)
            try:
                await asyncio.gather(
                    self._pump_twilio_to_openai(twilio_ws, openai_ws),
                    self._pump_openai_to_twilio(twilio_ws, openai_ws),
                )
            except WebSocketDisconnect:
                logger.info("Twilio websocket disconnected (call_id=%s)", self.recorder.call_id)
            except websockets.ConnectionClosed:
                logger.info("OpenAI Realtime connection closed (call_id=%s)", self.recorder.call_id)

    async def _configure_session(self, openai_ws) -> None:
        await openai_ws.send(json.dumps({
            "type": "session.update",
            "session": {
                "modalities": ["audio", "text"],
                "instructions": self.scenario.system_prompt,
                "voice": self.voice,
                "input_audio_format": "g711_ulaw",
                "output_audio_format": "g711_ulaw",
                "input_audio_transcription": {"model": "whisper-1"},
                "turn_detection": {
                    "type": "server_vad",
                    "threshold": 0.5,
                    "prefix_padding_ms": 300,
                    "silence_duration_ms": 500,
                },
            },
        }))
        # Our bot is the one placing the call, so it speaks first — kick off
        # a response immediately rather than waiting on the agent.
        await openai_ws.send(json.dumps({"type": "response.create"}))

    async def _pump_twilio_to_openai(self, twilio_ws: WebSocket, openai_ws: Any) -> None:
        async for raw in twilio_ws.iter_text():
            data = json.loads(raw)
            event = data.get("event")

            if event == "start":
                self.stream_sid = data["start"]["streamSid"]
                logger.info("Twilio stream started (stream_sid=%s)", self.stream_sid)

            elif event == "media":
                await openai_ws.send(json.dumps({
                    "type": "input_audio_buffer.append",
                    "audio": data["media"]["payload"],
                }))

            elif event == "stop":
                logger.info("Twilio stream stopped (stream_sid=%s)", self.stream_sid)
                break

    async def _pump_openai_to_twilio(self, twilio_ws: WebSocket, openai_ws: Any) -> None:
        async for raw in openai_ws:
            data = json.loads(raw)
            event_type = data.get("type")

            if event_type == EVENT_AUDIO_DELTA and self.stream_sid:
                await twilio_ws.send_text(json.dumps({
                    "event": "media",
                    "streamSid": self.stream_sid,
                    "media": {"payload": data["delta"]},
                }))

            elif event_type == EVENT_SPEECH_STARTED and self.stream_sid:
                # The real agent started talking over our bot (or vice
                # versa, from OpenAI's point of view) — tell Twilio to
                # drop whatever queued audio it has so playback catches up
                # instead of talking over the interruption for seconds.
                await twilio_ws.send_text(json.dumps({
                    "event": "clear",
                    "streamSid": self.stream_sid,
                }))

            elif event_type == EVENT_PATIENT_BOT_TRANSCRIPT_DONE:
                self.recorder.add_turn(speaker=SPEAKER_PATIENT_BOT, text=data.get("transcript", ""))

            elif event_type == EVENT_AGENT_UNDER_TEST_TRANSCRIPT_DONE:
                self.recorder.add_turn(speaker=SPEAKER_AGENT_UNDER_TEST, text=data.get("transcript", ""))

            elif event_type == EVENT_ERROR:
                logger.error("OpenAI Realtime error (call_id=%s): %s", self.recorder.call_id, data)
